#!/usr/bin/env python3
"""
Add Intel Arc (consumer, professional, datacenter) and Apple M-series GPUs
to the existing gpu_database.csv. Appends only — does not modify existing rows.
"""

import csv
import os
import sys

CSV_PATH = "/home/justin/Desktop/Programming/personal-GPU-database/gpu_database.csv"
TIMESTAMP = "2026-05-06T12:00"

# Column order must match the CSV header exactly (58 columns)
COLUMNS = [
    "gpu_name", "manufacturer", "brand", "category", "architecture", "gpu_chip",
    "release_year", "release_date", "discontinued", "process_node_nm",
    "transistors_billion", "die_size_mm2", "vram_gb", "vram_type",
    "vram_bus_width_bit", "memory_bandwidth_gbps", "cuda_cores",
    "stream_processors", "xe_cores", "tensor_cores", "rt_cores", "compute_units",
    "base_clock_mhz", "boost_clock_mhz", "fp32_tflops", "fp16_tflops",
    "bf16_tflops", "int8_tops", "tdp_watts", "recommended_psu_watts",
    "slot_width", "connector_type", "pcie_generation", "pcie_lanes",
    "nvlink_support", "display_outputs", "max_displays", "directx_version",
    "opencl_version", "cuda_compute_capability", "ecc_support",
    "price_usd_launch", "price_usd_new_current", "price_usd_newegg",
    "price_usd_amazon", "price_usd_bh", "price_usd_ebay_used",
    "link_newegg", "link_amazon", "link_bh", "link_ebay",
    "cost_per_gb_vram_new_usd", "cost_per_gb_vram_used_usd",
    "fp32_per_dollar_new", "fp32_per_dollar_used", "best_for", "notes",
    "last_modified"
]

N = "null"  # shorthand for null


def make_search_url(site, query):
    """Generate search URL for a given site and GPU name."""
    encoded = query.replace(" ", "%20")
    if site == "newegg":
        return f"https://www.newegg.com/p/pl?d={encoded}"
    elif site == "amazon":
        return f"https://www.amazon.com/s?k={encoded}"
    elif site == "bh":
        return f"https://www.bhphotovideo.com/c/search?q={encoded}"
    elif site == "ebay":
        return f"https://www.ebay.com/sch/i.html?_nkw={encoded}%20GPU&LH_Sold=1"
    return N


def calc_derived(row):
    """Calculate cost_per_gb and performance-per-dollar fields."""
    r = dict(row)

    def safe_float(val):
        if val == N or val is None:
            return None
        try:
            return float(val)
        except (ValueError, TypeError):
            return None

    def safe_int(val):
        if val == N or val is None:
            return None
        try:
            return int(float(val))
        except (ValueError, TypeError):
            return None

    price_new = safe_float(r.get("price_usd_new_current"))
    price_used = safe_float(r.get("price_usd_ebay_used"))
    vram = safe_float(r.get("vram_gb"))
    fp32 = safe_float(r.get("fp32_tflops"))

    # cost_per_gb_vram_new_usd
    if price_new and vram and vram > 0:
        r["cost_per_gb_vram_new_usd"] = round(price_new / vram, 2)
    else:
        r["cost_per_gb_vram_new_usd"] = N

    # cost_per_gb_vram_used_usd
    if price_used and vram and vram > 0:
        r["cost_per_gb_vram_used_usd"] = round(price_used / vram, 2)
    else:
        r["cost_per_gb_vram_used_usd"] = N

    # fp32_per_dollar_new
    if fp32 and price_new and price_new > 0:
        r["fp32_per_dollar_new"] = round(fp32 / price_new, 4)
    else:
        r["fp32_per_dollar_new"] = N

    # fp32_per_dollar_used
    if fp32 and price_used and price_used > 0:
        r["fp32_per_dollar_used"] = round(fp32 / price_used, 4)
    else:
        r["fp32_per_dollar_used"] = N

    return r


# =============================================================================
# DATA DEFINITIONS
# =============================================================================

# ---- Intel Arc Consumer GPUs ----

intel_consumer_gpus = [
    # Arc A770 16GB
    {
        "gpu_name": "Arc A770 16GB",
        "manufacturer": "Intel",
        "brand": "Intel Arc",
        "category": "consumer",
        "architecture": "Alchemist",
        "gpu_chip": "ACM-G10",
        "release_year": 2022,
        "release_date": "2022-10-12",
        "discontinued": "true",
        "process_node_nm": 6,
        "transistors_billion": 21.7,
        "die_size_mm2": 406,
        "vram_gb": 16,
        "vram_type": "GDDR6",
        "vram_bus_width_bit": 256,
        "memory_bandwidth_gbps": 512,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": 32,
        "tensor_cores": N,
        "rt_cores": 32,
        "compute_units": N,
        "base_clock_mhz": 2100,
        "boost_clock_mhz": 2100,
        "fp32_tflops": 17.2,
        "fp16_tflops": 17.2,
        "bf16_tflops": 17.2,
        "int8_tops": N,
        "tdp_watts": 225,
        "recommended_psu_watts": 600,
        "slot_width": "2-slot",
        "connector_type": "8-pin",
        "pcie_generation": 4,
        "pcie_lanes": 16,
        "nvlink_support": "false",
        "display_outputs": "3x DP 2.0 + 1x HDMI 2.1",
        "max_displays": 4,
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": 329,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": 280,
        "price_usd_bh": N,
        "price_usd_ebay_used": 150,
        "link_newegg": make_search_url("newegg", "Intel Arc A770 16GB"),
        "link_amazon": make_search_url("amazon", "Intel Arc A770 16GB"),
        "link_bh": make_search_url("bh", "Intel Arc A770 16GB"),
        "link_ebay": make_search_url("ebay", "Intel Arc A770 16GB"),
        "best_for": "gaming,budget,ai_inference",
        "notes": "Discontinued; first-gen Intel Arc flagship",
    },
    # Arc A770 8GB (Limited Edition)
    {
        "gpu_name": "Arc A770 8GB",
        "manufacturer": "Intel",
        "brand": "Intel Arc",
        "category": "consumer",
        "architecture": "Alchemist",
        "gpu_chip": "ACM-G10",
        "release_year": 2022,
        "release_date": "2022-10-12",
        "discontinued": "true",
        "process_node_nm": 6,
        "transistors_billion": 21.7,
        "die_size_mm2": 406,
        "vram_gb": 8,
        "vram_type": "GDDR6",
        "vram_bus_width_bit": 256,
        "memory_bandwidth_gbps": 512,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": 32,
        "tensor_cores": N,
        "rt_cores": 32,
        "compute_units": N,
        "base_clock_mhz": 2100,
        "boost_clock_mhz": 2100,
        "fp32_tflops": 17.2,
        "fp16_tflops": 17.2,
        "bf16_tflops": 17.2,
        "int8_tops": N,
        "tdp_watts": 225,
        "recommended_psu_watts": 600,
        "slot_width": "2-slot",
        "connector_type": "8-pin",
        "pcie_generation": 4,
        "pcie_lanes": 16,
        "nvlink_support": "false",
        "display_outputs": "3x DP 2.0 + 1x HDMI 2.1",
        "max_displays": 4,
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": 299,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": 130,
        "link_newegg": make_search_url("newegg", "Intel Arc A770 8GB"),
        "link_amazon": make_search_url("amazon", "Intel Arc A770 8GB"),
        "link_bh": make_search_url("bh", "Intel Arc A770 8GB"),
        "link_ebay": make_search_url("ebay", "Intel Arc A770 8GB"),
        "best_for": "gaming,budget",
        "notes": "Discontinued; Intel Limited Edition variant with 8GB GDDR6",
    },
    # Arc A750
    {
        "gpu_name": "Arc A750",
        "manufacturer": "Intel",
        "brand": "Intel Arc",
        "category": "consumer",
        "architecture": "Alchemist",
        "gpu_chip": "ACM-G10",
        "release_year": 2022,
        "release_date": "2022-10-12",
        "discontinued": "true",
        "process_node_nm": 6,
        "transistors_billion": 21.7,
        "die_size_mm2": 406,
        "vram_gb": 8,
        "vram_type": "GDDR6",
        "vram_bus_width_bit": 256,
        "memory_bandwidth_gbps": 512,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": 28,
        "tensor_cores": N,
        "rt_cores": 28,
        "compute_units": N,
        "base_clock_mhz": 2050,
        "boost_clock_mhz": 2050,
        "fp32_tflops": 13.6,
        "fp16_tflops": 13.6,
        "bf16_tflops": 13.6,
        "int8_tops": N,
        "tdp_watts": 225,
        "recommended_psu_watts": 550,
        "slot_width": "2-slot",
        "connector_type": "8-pin",
        "pcie_generation": 4,
        "pcie_lanes": 16,
        "nvlink_support": "false",
        "display_outputs": "3x DP 2.0 + 1x HDMI 2.1",
        "max_displays": 4,
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": 289,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": 110,
        "link_newegg": make_search_url("newegg", "Intel Arc A750"),
        "link_amazon": make_search_url("amazon", "Intel Arc A750"),
        "link_bh": make_search_url("bh", "Intel Arc A750"),
        "link_ebay": make_search_url("ebay", "Intel Arc A750"),
        "best_for": "gaming,budget",
        "notes": "Discontinued; price-cut to $249 in early 2023",
    },
    # Arc A580
    {
        "gpu_name": "Arc A580",
        "manufacturer": "Intel",
        "brand": "Intel Arc",
        "category": "consumer",
        "architecture": "Alchemist",
        "gpu_chip": "ACM-G10",
        "release_year": 2023,
        "release_date": "2023-09-13",
        "discontinued": "true",
        "process_node_nm": 6,
        "transistors_billion": 21.7,
        "die_size_mm2": 406,
        "vram_gb": 8,
        "vram_type": "GDDR6",
        "vram_bus_width_bit": 256,
        "memory_bandwidth_gbps": 512,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": 24,
        "tensor_cores": N,
        "rt_cores": 24,
        "compute_units": N,
        "base_clock_mhz": 1700,
        "boost_clock_mhz": 1700,
        "fp32_tflops": 12.0,
        "fp16_tflops": 12.0,
        "bf16_tflops": 12.0,
        "int8_tops": N,
        "tdp_watts": 185,
        "recommended_psu_watts": 500,
        "slot_width": "2-slot",
        "connector_type": "8-pin",
        "pcie_generation": 4,
        "pcie_lanes": 16,
        "nvlink_support": "false",
        "display_outputs": "3x DP 2.0 + 1x HDMI 2.1",
        "max_displays": 4,
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": 179,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": 95,
        "link_newegg": make_search_url("newegg", "Intel Arc A580"),
        "link_amazon": make_search_url("amazon", "Intel Arc A580"),
        "link_bh": make_search_url("bh", "Intel Arc A580"),
        "link_ebay": make_search_url("ebay", "Intel Arc A580"),
        "best_for": "gaming,budget",
        "notes": "Discontinued; late-launch budget Alchemist card",
    },
    # Arc A380
    {
        "gpu_name": "Arc A380",
        "manufacturer": "Intel",
        "brand": "Intel Arc",
        "category": "consumer",
        "architecture": "Alchemist",
        "gpu_chip": "ACM-G11",
        "release_year": 2022,
        "release_date": "2022-06-15",
        "discontinued": "true",
        "process_node_nm": 6,
        "transistors_billion": 7.2,
        "die_size_mm2": 157,
        "vram_gb": 6,
        "vram_type": "GDDR6",
        "vram_bus_width_bit": 96,
        "memory_bandwidth_gbps": 186,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": 8,
        "tensor_cores": N,
        "rt_cores": 8,
        "compute_units": N,
        "base_clock_mhz": 2000,
        "boost_clock_mhz": 2450,
        "fp32_tflops": 5.8,
        "fp16_tflops": 5.8,
        "bf16_tflops": 5.8,
        "int8_tops": N,
        "tdp_watts": 75,
        "recommended_psu_watts": 400,
        "slot_width": "2-slot",
        "connector_type": "None",
        "pcie_generation": 4,
        "pcie_lanes": 8,
        "nvlink_support": "false",
        "display_outputs": "3x DP 2.0 + 1x HDMI 2.1",
        "max_displays": 4,
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": 139,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": 60,
        "link_newegg": make_search_url("newegg", "Intel Arc A380"),
        "link_amazon": make_search_url("amazon", "Intel Arc A380"),
        "link_bh": make_search_url("bh", "Intel Arc A380"),
        "link_ebay": make_search_url("ebay", "Intel Arc A380"),
        "best_for": "gaming,budget",
        "notes": "Discontinued; entry-level Alchemist; no external power needed on some models",
    },
    # Arc B580 (Battlemage)
    {
        "gpu_name": "Arc B580",
        "manufacturer": "Intel",
        "brand": "Intel Arc",
        "category": "consumer",
        "architecture": "Battlemage",
        "gpu_chip": "BMG-G21",
        "release_year": 2024,
        "release_date": "2024-12-13",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 19.6,
        "die_size_mm2": 272,
        "vram_gb": 12,
        "vram_type": "GDDR6",
        "vram_bus_width_bit": 192,
        "memory_bandwidth_gbps": 456,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": 20,
        "tensor_cores": N,
        "rt_cores": 20,
        "compute_units": N,
        "base_clock_mhz": 2300,
        "boost_clock_mhz": 2670,
        "fp32_tflops": 23.2,
        "fp16_tflops": 23.2,
        "bf16_tflops": 23.2,
        "int8_tops": N,
        "tdp_watts": 150,
        "recommended_psu_watts": 500,
        "slot_width": "2-slot",
        "connector_type": "8-pin",
        "pcie_generation": 4,
        "pcie_lanes": 8,
        "nvlink_support": "false",
        "display_outputs": "3x DP 2.1 + 1x HDMI 2.1",
        "max_displays": 4,
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": 249,
        "price_usd_new_current": 249,
        "price_usd_newegg": 249,
        "price_usd_amazon": 249,
        "price_usd_bh": 249,
        "price_usd_ebay_used": 210,
        "link_newegg": make_search_url("newegg", "Intel Arc B580"),
        "link_amazon": make_search_url("amazon", "Intel Arc B580"),
        "link_bh": make_search_url("bh", "Intel Arc B580"),
        "link_ebay": make_search_url("ebay", "Intel Arc B580"),
        "best_for": "gaming,budget,ai_inference",
        "notes": "Battlemage architecture; best budget GPU of 2024; 12GB VRAM at $249",
    },
    # Arc B570 (Battlemage)
    {
        "gpu_name": "Arc B570",
        "manufacturer": "Intel",
        "brand": "Intel Arc",
        "category": "consumer",
        "architecture": "Battlemage",
        "gpu_chip": "BMG-G21",
        "release_year": 2025,
        "release_date": "2025-01-16",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 19.6,
        "die_size_mm2": 272,
        "vram_gb": 10,
        "vram_type": "GDDR6",
        "vram_bus_width_bit": 160,
        "memory_bandwidth_gbps": 380,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": 16,
        "tensor_cores": N,
        "rt_cores": 16,
        "compute_units": N,
        "base_clock_mhz": 2300,
        "boost_clock_mhz": 2500,
        "fp32_tflops": 18.4,
        "fp16_tflops": 18.4,
        "bf16_tflops": 18.4,
        "int8_tops": N,
        "tdp_watts": 150,
        "recommended_psu_watts": 500,
        "slot_width": "2-slot",
        "connector_type": "8-pin",
        "pcie_generation": 4,
        "pcie_lanes": 8,
        "nvlink_support": "false",
        "display_outputs": "3x DP 2.1 + 1x HDMI 2.1",
        "max_displays": 4,
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": 219,
        "price_usd_new_current": 219,
        "price_usd_newegg": 219,
        "price_usd_amazon": 219,
        "price_usd_bh": 219,
        "price_usd_ebay_used": 180,
        "link_newegg": make_search_url("newegg", "Intel Arc B570"),
        "link_amazon": make_search_url("amazon", "Intel Arc B570"),
        "link_bh": make_search_url("bh", "Intel Arc B570"),
        "link_ebay": make_search_url("ebay", "Intel Arc B570"),
        "best_for": "gaming,budget",
        "notes": "Battlemage architecture; cut-down B580 with 10GB VRAM",
    },
]

# ---- Intel Arc Professional GPUs ----

intel_professional_gpus = [
    # Arc A40
    {
        "gpu_name": "Arc A40",
        "manufacturer": "Intel",
        "brand": "Intel Arc Pro",
        "category": "professional",
        "architecture": "Alchemist",
        "gpu_chip": "ACM-G11",
        "release_year": 2023,
        "release_date": "2023-04-11",
        "discontinued": "false",
        "process_node_nm": 6,
        "transistors_billion": 7.2,
        "die_size_mm2": 157,
        "vram_gb": 6,
        "vram_type": "GDDR6",
        "vram_bus_width_bit": 96,
        "memory_bandwidth_gbps": 186,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": 8,
        "tensor_cores": N,
        "rt_cores": 8,
        "compute_units": N,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 5.8,
        "fp16_tflops": 5.8,
        "bf16_tflops": 5.8,
        "int8_tops": N,
        "tdp_watts": 50,
        "recommended_psu_watts": N,
        "slot_width": "single-slot",
        "connector_type": "None",
        "pcie_generation": 4,
        "pcie_lanes": 16,
        "nvlink_support": "false",
        "display_outputs": "4x mini-DP",
        "max_displays": 4,
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": 149,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": make_search_url("newegg", "Intel Arc A40"),
        "link_amazon": make_search_url("amazon", "Intel Arc A40"),
        "link_bh": make_search_url("bh", "Intel Arc A40"),
        "link_ebay": make_search_url("ebay", "Intel Arc A40"),
        "best_for": "workstation,rendering",
        "notes": "Professional workstation card; low-profile single-slot; passively cooled",
    },
    # Arc A30
    {
        "gpu_name": "Arc A30",
        "manufacturer": "Intel",
        "brand": "Intel Arc Pro",
        "category": "professional",
        "architecture": "Alchemist",
        "gpu_chip": "ACM-G11",
        "release_year": 2023,
        "release_date": "2023-04-11",
        "discontinued": "false",
        "process_node_nm": 6,
        "transistors_billion": 7.2,
        "die_size_mm2": 157,
        "vram_gb": 6,
        "vram_type": "GDDR6",
        "vram_bus_width_bit": 96,
        "memory_bandwidth_gbps": 186,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": 8,
        "tensor_cores": N,
        "rt_cores": 8,
        "compute_units": N,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 4.8,
        "fp16_tflops": 4.8,
        "bf16_tflops": 4.8,
        "int8_tops": N,
        "tdp_watts": 50,
        "recommended_psu_watts": N,
        "slot_width": "single-slot",
        "connector_type": "None",
        "pcie_generation": 4,
        "pcie_lanes": 16,
        "nvlink_support": "false",
        "display_outputs": "4x mini-DP",
        "max_displays": 4,
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": 149,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": make_search_url("newegg", "Intel Arc A30"),
        "link_amazon": make_search_url("amazon", "Intel Arc A30"),
        "link_bh": make_search_url("bh", "Intel Arc A30"),
        "link_ebay": make_search_url("ebay", "Intel Arc A30"),
        "best_for": "workstation,rendering",
        "notes": "Professional workstation card; low-profile single-slot; passively cooled; slightly lower clocks than A40",
    },
]

# ---- Intel Datacenter Accelerators ----

intel_datacenter_gpus = [
    # Gaudi 2
    {
        "gpu_name": "Gaudi 2",
        "manufacturer": "Intel",
        "brand": "Intel Gaudi",
        "category": "datacenter",
        "architecture": "Gaudi 2",
        "gpu_chip": "Gaudi 2",
        "release_year": 2022,
        "release_date": "2022-05-26",
        "discontinued": "false",
        "process_node_nm": 7,
        "transistors_billion": N,
        "die_size_mm2": N,
        "vram_gb": 96,
        "vram_type": "HBM2e",
        "vram_bus_width_bit": 6144,
        "memory_bandwidth_gbps": 2460,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": N,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 45.1,
        "fp16_tflops": 362,
        "bf16_tflops": 362,
        "int8_tops": 724,
        "tdp_watts": 600,
        "recommended_psu_watts": N,
        "slot_width": "dual-slot",
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": "false",
        "display_outputs": "0",
        "max_displays": 0,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "true",
        "price_usd_launch": 65000,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "ai_training,ai_inference,server",
        "notes": "AI training accelerator; 24 integrated tensor processor cores; 96GB HBM2e; acquired via Habana Labs",
    },
    # Gaudi 3
    {
        "gpu_name": "Gaudi 3",
        "manufacturer": "Intel",
        "brand": "Intel Gaudi",
        "category": "datacenter",
        "architecture": "Gaudi 3",
        "gpu_chip": "Gaudi 3",
        "release_year": 2024,
        "release_date": "2024-12-01",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": N,
        "die_size_mm2": N,
        "vram_gb": 128,
        "vram_type": "HBM3",
        "vram_bus_width_bit": 8192,
        "memory_bandwidth_gbps": 3277,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": N,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 91.6,
        "fp16_tflops": 733,
        "bf16_tflops": 733,
        "int8_tops": 1466,
        "tdp_watts": 900,
        "recommended_psu_watts": N,
        "slot_width": "dual-slot",
        "connector_type": N,
        "pcie_generation": 5,
        "pcie_lanes": 16,
        "nvlink_support": "false",
        "display_outputs": "0",
        "max_displays": 0,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "true",
        "price_usd_launch": 125000,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "ai_training,ai_inference,server",
        "notes": "AI training accelerator; 8 integrated tensor processor cores; 128GB HBM3; 5nm process",
    },
]

# ---- Apple M-Series Integrated GPUs ----
# Single entry per chip tier using max GPU core count and max unified memory config

apple_gpus = [
    # M1
    {
        "gpu_name": "Apple M1 GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M1",
        "gpu_chip": "M1",
        "release_year": 2020,
        "release_date": "2020-11-17",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 16.0,
        "die_size_mm2": N,
        "vram_gb": 16,
        "vram_type": "Unified LPDDR4X",
        "vram_bus_width_bit": 128,
        "memory_bandwidth_gbps": 68.25,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 8,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 2.6,
        "fp16_tflops": 5.2,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 2,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,mobile",
        "notes": "8-core GPU; unified memory; max 16GB config; integrated into M1 SoC",
    },
    # M1 Pro
    {
        "gpu_name": "Apple M1 Pro GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M1 Pro",
        "gpu_chip": "M1 Pro",
        "release_year": 2021,
        "release_date": "2021-10-26",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 33.7,
        "die_size_mm2": N,
        "vram_gb": 32,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 256,
        "memory_bandwidth_gbps": 200,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 16,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 5.2,
        "fp16_tflops": 10.4,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 2,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,mobile",
        "notes": "16-core GPU; unified memory; max 32GB config; integrated into M1 Pro SoC",
    },
    # M1 Max
    {
        "gpu_name": "Apple M1 Max GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M1 Max",
        "gpu_chip": "M1 Max",
        "release_year": 2021,
        "release_date": "2021-10-26",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 57.0,
        "die_size_mm2": N,
        "vram_gb": 64,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 512,
        "memory_bandwidth_gbps": 400,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 24,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 10.4,
        "fp16_tflops": 20.8,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 4,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,ai_inference,mobile",
        "notes": "24-core GPU; unified memory; max 64GB config; integrated into M1 Max SoC",
    },
    # M1 Ultra
    {
        "gpu_name": "Apple M1 Ultra GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M1 Ultra",
        "gpu_chip": "M1 Ultra",
        "release_year": 2022,
        "release_date": "2022-03-08",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 114.0,
        "die_size_mm2": N,
        "vram_gb": 128,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 819,
        "memory_bandwidth_gbps": 800,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 48,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 20.8,
        "fp16_tflops": 41.6,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 5,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,ai_inference",
        "notes": "48-core GPU; unified memory; max 128GB config; dual M1 Max die via UltraFusion",
    },
    # M2
    {
        "gpu_name": "Apple M2 GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M2",
        "gpu_chip": "M2",
        "release_year": 2022,
        "release_date": "2022-06-24",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 20.0,
        "die_size_mm2": N,
        "vram_gb": 24,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 128,
        "memory_bandwidth_gbps": 100,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 10,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 3.6,
        "fp16_tflops": 7.2,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 2,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,mobile",
        "notes": "10-core GPU; unified memory; max 24GB config; integrated into M2 SoC",
    },
    # M2 Pro
    {
        "gpu_name": "Apple M2 Pro GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M2 Pro",
        "gpu_chip": "M2 Pro",
        "release_year": 2023,
        "release_date": "2023-01-17",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 40.0,
        "die_size_mm2": N,
        "vram_gb": 32,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 256,
        "memory_bandwidth_gbps": 200,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 19,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 6.8,
        "fp16_tflops": 13.6,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 2,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,mobile",
        "notes": "19-core GPU; unified memory; max 32GB config; integrated into M2 Pro SoC",
    },
    # M2 Max
    {
        "gpu_name": "Apple M2 Max GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M2 Max",
        "gpu_chip": "M2 Max",
        "release_year": 2023,
        "release_date": "2023-01-17",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 67.0,
        "die_size_mm2": N,
        "vram_gb": 96,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 512,
        "memory_bandwidth_gbps": 400,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 38,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 13.6,
        "fp16_tflops": 27.2,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 4,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,ai_inference,mobile",
        "notes": "38-core GPU; unified memory; max 96GB config; integrated into M2 Max SoC",
    },
    # M2 Ultra
    {
        "gpu_name": "Apple M2 Ultra GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M2 Ultra",
        "gpu_chip": "M2 Ultra",
        "release_year": 2023,
        "release_date": "2023-06-05",
        "discontinued": "false",
        "process_node_nm": 5,
        "transistors_billion": 134.0,
        "die_size_mm2": N,
        "vram_gb": 192,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 819,
        "memory_bandwidth_gbps": 800,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 76,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 27.2,
        "fp16_tflops": 54.4,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 8,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,ai_inference",
        "notes": "76-core GPU; unified memory; max 192GB config; dual M2 Max die via UltraFusion; Mac Pro/Mac Studio",
    },
    # M3
    {
        "gpu_name": "Apple M3 GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M3",
        "gpu_chip": "M3",
        "release_year": 2023,
        "release_date": "2023-11-07",
        "discontinued": "false",
        "process_node_nm": 3,
        "transistors_billion": 25.0,
        "die_size_mm2": N,
        "vram_gb": 24,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 128,
        "memory_bandwidth_gbps": 100,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 10,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 4.2,
        "fp16_tflops": 8.4,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 2,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,mobile",
        "notes": "10-core GPU; unified memory; max 24GB config; hardware ray tracing; first 3nm Apple SoC",
    },
    # M3 Pro
    {
        "gpu_name": "Apple M3 Pro GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M3 Pro",
        "gpu_chip": "M3 Pro",
        "release_year": 2023,
        "release_date": "2023-11-07",
        "discontinued": "false",
        "process_node_nm": 3,
        "transistors_billion": 37.0,
        "die_size_mm2": N,
        "vram_gb": 36,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 256,
        "memory_bandwidth_gbps": 150,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 18,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 7.0,
        "fp16_tflops": 14.0,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 2,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,mobile",
        "notes": "18-core GPU; unified memory; max 36GB config; hardware ray tracing",
    },
    # M3 Max
    {
        "gpu_name": "Apple M3 Max GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M3 Max",
        "gpu_chip": "M3 Max",
        "release_year": 2023,
        "release_date": "2023-11-07",
        "discontinued": "false",
        "process_node_nm": 3,
        "transistors_billion": 92.0,
        "die_size_mm2": N,
        "vram_gb": 128,
        "vram_type": "Unified LPDDR5",
        "vram_bus_width_bit": 512,
        "memory_bandwidth_gbps": 400,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 40,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 15.8,
        "fp16_tflops": 31.6,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 4,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,ai_inference,mobile",
        "notes": "40-core GPU; unified memory; max 128GB config; hardware ray tracing",
    },
    # M4
    {
        "gpu_name": "Apple M4 GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M4",
        "gpu_chip": "M4",
        "release_year": 2024,
        "release_date": "2024-05-07",
        "discontinued": "false",
        "process_node_nm": 3,
        "transistors_billion": 28.0,
        "die_size_mm2": N,
        "vram_gb": 32,
        "vram_type": "Unified LPDDR5X",
        "vram_bus_width_bit": 128,
        "memory_bandwidth_gbps": 120,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 10,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 4.8,
        "fp16_tflops": 9.6,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 2,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,mobile",
        "notes": "10-core GPU; unified memory; max 32GB config (iPad Pro); hardware ray tracing",
    },
    # M4 Pro
    {
        "gpu_name": "Apple M4 Pro GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M4 Pro",
        "gpu_chip": "M4 Pro",
        "release_year": 2024,
        "release_date": "2024-11-08",
        "discontinued": "false",
        "process_node_nm": 3,
        "transistors_billion": 45.0,
        "die_size_mm2": N,
        "vram_gb": 48,
        "vram_type": "Unified LPDDR5X",
        "vram_bus_width_bit": 256,
        "memory_bandwidth_gbps": 273,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 20,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 9.2,
        "fp16_tflops": 18.4,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 2,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,mobile",
        "notes": "20-core GPU; unified memory; max 48GB config; hardware ray tracing; Thunderbolt 5",
    },
    # M4 Max
    {
        "gpu_name": "Apple M4 Max GPU",
        "manufacturer": "Apple",
        "brand": "Apple Silicon",
        "category": "integrated",
        "architecture": "M4 Max",
        "gpu_chip": "M4 Max",
        "release_year": 2024,
        "release_date": "2024-11-08",
        "discontinued": "false",
        "process_node_nm": 3,
        "transistors_billion": 92.0,
        "die_size_mm2": N,
        "vram_gb": 128,
        "vram_type": "Unified LPDDR5X",
        "vram_bus_width_bit": 512,
        "memory_bandwidth_gbps": 546,
        "cuda_cores": N,
        "stream_processors": N,
        "xe_cores": N,
        "tensor_cores": N,
        "rt_cores": N,
        "compute_units": 40,
        "base_clock_mhz": N,
        "boost_clock_mhz": N,
        "fp32_tflops": 18.5,
        "fp16_tflops": 37.0,
        "bf16_tflops": N,
        "int8_tops": N,
        "tdp_watts": N,
        "recommended_psu_watts": N,
        "slot_width": N,
        "connector_type": N,
        "pcie_generation": N,
        "pcie_lanes": N,
        "nvlink_support": N,
        "display_outputs": N,
        "max_displays": 4,
        "directx_version": N,
        "opencl_version": N,
        "cuda_compute_capability": N,
        "ecc_support": "false",
        "price_usd_launch": N,
        "price_usd_new_current": N,
        "price_usd_newegg": N,
        "price_usd_amazon": N,
        "price_usd_bh": N,
        "price_usd_ebay_used": N,
        "link_newegg": N,
        "link_amazon": N,
        "link_bh": N,
        "link_ebay": N,
        "best_for": "compute,rendering,ai_inference,mobile",
        "notes": "40-core GPU; unified memory; max 128GB config; hardware ray tracing; Thunderbolt 5",
    },
]


def build_row(gpu_data):
    """Build a complete row dict with all 58 columns, filling missing with null."""
    row = {}
    for col in COLUMNS:
        if col == "last_modified":
            row[col] = TIMESTAMP
        elif col in ("cost_per_gb_vram_new_usd", "cost_per_gb_vram_used_usd",
                      "fp32_per_dollar_new", "fp32_per_dollar_used"):
            row[col] = N  # will be calculated
        else:
            row[col] = gpu_data.get(col, N)
    # Calculate derived fields
    row = calc_derived(row)
    return row


def rows_match(r1, r2):
    """Check if two rows have the same gpu_name."""
    return r1.get("gpu_name") == r2.get("gpu_name")


def main():
    # Read existing CSV
    if not os.path.exists(CSV_PATH):
        print(f"ERROR: CSV file not found at {CSV_PATH}")
        sys.exit(1)

    with open(CSV_PATH, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        existing_rows = list(reader)
        fieldnames = reader.fieldnames

    print(f"Existing rows: {len(existing_rows)}")
    existing_names = {r["gpu_name"] for r in existing_rows}

    # Combine all new GPU data
    all_new_data = (
        intel_consumer_gpus
        + intel_professional_gpus
        + intel_datacenter_gpus
        + apple_gpus
    )

    # Build complete rows and filter out duplicates
    new_rows = []
    for gpu in all_new_data:
        row = build_row(gpu)
        if row["gpu_name"] in existing_names:
            print(f"  SKIP (already exists): {row['gpu_name']}")
            continue
        new_rows.append(row)

    if not new_rows:
        print("No new rows to add.")
        return

    # Append new rows in batches of 15
    BATCH_SIZE = 15
    total_added = 0

    combined_rows = existing_rows + new_rows

    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for i, row in enumerate(combined_rows):
            writer.writerow(row)
            if i >= len(existing_rows):
                total_added += 1

    print(f"\nTotal new rows added: {total_added}")
    print(f"Total rows in CSV: {len(combined_rows)}")

    # Summary breakdown
    intel_consumer_added = sum(
        1 for r in new_rows
        if r.get("manufacturer") == "Intel" and r.get("category") == "consumer"
    )
    intel_pro_added = sum(
        1 for r in new_rows
        if r.get("manufacturer") == "Intel" and r.get("category") == "professional"
    )
    intel_dc_added = sum(
        1 for r in new_rows
        if r.get("manufacturer") == "Intel" and r.get("category") == "datacenter"
    )
    apple_added = sum(
        1 for r in new_rows if r.get("manufacturer") == "Apple"
    )

    print(f"\nBreakdown:")
    print(f"  Intel Arc Consumer:       {intel_consumer_added}")
    print(f"  Intel Arc Professional:   {intel_pro_added}")
    print(f"  Intel Datacenter:         {intel_dc_added}")
    print(f"  Apple M-Series:           {apple_added}")

    # Print GPU names added
    print(f"\nGPUs added:")
    for r in new_rows:
        derived_str = ""
        pn = r.get("price_usd_new_current")
        fp32 = r.get("fp32_tflops")
        if pn != N and fp32 != N:
            derived_str = f" [${pn}, {fp32} TFLOPS]"
        print(f"  - {r['gpu_name']}{derived_str}")


if __name__ == "__main__":
    main()
