#!/usr/bin/env python3
"""
Fill in specs for name-only NVIDIA cards in the GPU database.
Only fills fields that are currently null/empty.
"""

import csv
import os
from datetime import datetime

CSV_PATH = "/home/justin/Desktop/Programming/personal-GPU-database/gpu_database.csv"
TIMESTAMP = datetime.now().strftime("%Y-%m-%dT%H:%M")

# Define all cards and their specs.
# Keys are gpu_name values to match in the CSV.
# For pre-CUDA cards (GeForce 6 and earlier), cuda_cores should be null.
# VRAM is in GB (e.g., 0.25 = 256MB, 0.125 = 128MB, 0.0625 = 64MB, 0.03125 = 32MB).

CARDS = {
    # ============ GeForce 6 series ============
    "GeForce 6800 Ultra": {
        "gpu_chip": "NV40",
        "release_year": "2004",
        "release_date": "2004-04-14",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.25",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "256",
        "base_clock_mhz": "425",
        "tdp_watts": "110",
        "price_usd_launch": "499",
        "directx_version": "9.0c",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified. Flagship of GeForce 6 series.",
    },
    "GeForce 6800 GT": {
        "gpu_chip": "NV40",
        "release_year": "2004",
        "release_date": "2004-04-14",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.25",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "256",
        "base_clock_mhz": "350",
        "tdp_watts": "89",
        "price_usd_launch": "399",
        "directx_version": "9.0c",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce 6800 GS": {
        "gpu_chip": "NV42",
        "release_year": "2005",
        "release_date": "2005-09-21",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.25",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "256",
        "base_clock_mhz": "350",
        "tdp_watts": "75",
        "price_usd_launch": "299",
        "directx_version": "9.0c",
        "pcie_generation": "PCIe 1.0",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce 6800 XT": {
        "gpu_chip": "NV40",
        "release_year": "2004",
        "release_date": "2004-10-11",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.125",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "256",
        "base_clock_mhz": "325",
        "tdp_watts": "60",
        "directx_version": "9.0c",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce 6800 LE": {
        "gpu_chip": "NV40",
        "release_year": "2004",
        "release_date": "2004-08-12",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.125",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "256",
        "base_clock_mhz": "300",
        "tdp_watts": "50",
        "directx_version": "9.0c",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce 6600 GT": {
        "gpu_chip": "NV43",
        "release_year": "2004",
        "release_date": "2004-09-21",
        "discontinued": "true",
        "process_node_nm": "110",
        "vram_gb": "0.125",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "500",
        "tdp_watts": "57",
        "price_usd_launch": "199",
        "directx_version": "9.0c",
        "pcie_generation": "PCIe 1.0",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce 6600": {
        "gpu_chip": "NV43",
        "release_year": "2004",
        "release_date": "2004-09-21",
        "discontinued": "true",
        "process_node_nm": "110",
        "vram_gb": "0.125",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "300",
        "tdp_watts": "36",
        "directx_version": "9.0c",
        "pcie_generation": "PCIe 1.0",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce 6600 LE": {
        "gpu_chip": "NV43",
        "release_year": "2004",
        "release_date": "2004-09-21",
        "discontinued": "true",
        "process_node_nm": "110",
        "vram_gb": "0.125",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "300",
        "tdp_watts": "28",
        "directx_version": "9.0c",
        "pcie_generation": "PCIe 1.0",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce 6200": {
        "gpu_chip": "NV44",
        "release_year": "2004",
        "release_date": "2004-10-11",
        "discontinued": "true",
        "process_node_nm": "110",
        "vram_gb": "0.125",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "300",
        "tdp_watts": "30",
        "directx_version": "9.0c",
        "pcie_generation": "PCIe 1.0",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified. Budget card.",
    },

    # ============ GeForce FX series ============
    "GeForce FX 5950 Ultra": {
        "gpu_chip": "NV38",
        "release_year": "2003",
        "release_date": "2003-10-23",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.25",
        "vram_type": "GDDR2",
        "vram_bus_width_bit": "256",
        "base_clock_mhz": "475",
        "tdp_watts": "90",
        "price_usd_launch": "499",
        "directx_version": "9.0a",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce FX 5900": {
        "gpu_chip": "NV35",
        "release_year": "2003",
        "release_date": "2003-05-19",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.125",
        "vram_type": "GDDR2",
        "vram_bus_width_bit": "256",
        "base_clock_mhz": "400",
        "tdp_watts": "60",
        "directx_version": "9.0a",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce FX 5800 Ultra": {
        "gpu_chip": "NV30",
        "release_year": "2002",
        "release_date": "2002-11-18",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.125",
        "vram_type": "GDDR2",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "500",
        "tdp_watts": "80",
        "price_usd_launch": "399",
        "directx_version": "9.0a",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified. Notorious for loud 'Dustbuster' cooler.",
    },
    "GeForce FX 5700 Ultra": {
        "gpu_chip": "NV36",
        "release_year": "2003",
        "release_date": "2003-10-23",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.125",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "475",
        "tdp_watts": "55",
        "price_usd_launch": "199",
        "directx_version": "9.0a",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce FX 5600": {
        "gpu_chip": "NV31",
        "release_year": "2003",
        "release_date": "2003-03-12",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.125",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "325",
        "tdp_watts": "37",
        "directx_version": "9.0a",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce FX 5200": {
        "gpu_chip": "NV34",
        "release_year": "2003",
        "release_date": "2003-03-12",
        "discontinued": "true",
        "process_node_nm": "130",
        "vram_gb": "0.125",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "250",
        "tdp_watts": "25",
        "price_usd_launch": "79",
        "directx_version": "9.0a",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified. Budget card.",
    },

    # ============ GeForce4 series ============
    "GeForce4 Ti 4600": {
        "gpu_chip": "NV25",
        "release_year": "2002",
        "release_date": "2002-02-06",
        "discontinued": "true",
        "process_node_nm": "150",
        "vram_gb": "0.125",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "300",
        "tdp_watts": "50",
        "price_usd_launch": "399",
        "directx_version": "8.1",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified.",
    },
    "GeForce4 Ti 4200": {
        "gpu_chip": "NV25",
        "release_year": "2002",
        "release_date": "2002-04-15",
        "discontinued": "true",
        "process_node_nm": "150",
        "vram_gb": "0.125",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "250",
        "tdp_watts": "42",
        "price_usd_launch": "199",
        "directx_version": "8.1",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; pixel/vertex shaders, not unified. Legendary price/performance.",
    },
    "GeForce4 MX 460": {
        "gpu_chip": "NV17",
        "release_year": "2002",
        "release_date": "2002-02-06",
        "discontinued": "true",
        "process_node_nm": "150",
        "vram_gb": "0.0625",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "300",
        "tdp_watts": "30",
        "directx_version": "7.0",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; fixed-function T&L, no pixel shaders.",
    },

    # ============ GeForce3 series ============
    "GeForce3 Ti 500": {
        "gpu_chip": "NV20",
        "release_year": "2001",
        "release_date": "2001-10-01",
        "discontinued": "true",
        "process_node_nm": "150",
        "vram_gb": "0.0625",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "240",
        "tdp_watts": "45",
        "price_usd_launch": "399",
        "directx_version": "8.1",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; first programmable pixel shader GPU.",
    },

    # ============ GeForce2 series ============
    "GeForce2 Ultra": {
        "gpu_chip": "NV15",
        "release_year": "2000",
        "release_date": "2000-09-07",
        "discontinued": "true",
        "process_node_nm": "180",
        "vram_gb": "0.0625",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "250",
        "tdp_watts": "35",
        "directx_version": "7.0",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; hardware T&L, fixed-function pipeline.",
    },
    "GeForce2 GTS": {
        "gpu_chip": "NV15",
        "release_year": "2000",
        "release_date": "2000-04-26",
        "discontinued": "true",
        "process_node_nm": "180",
        "vram_gb": "0.03125",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "200",
        "tdp_watts": "25",
        "directx_version": "7.0",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; hardware T&L, fixed-function pipeline.",
    },
    "GeForce2 MX": {
        "gpu_chip": "NV11",
        "release_year": "2000",
        "release_date": "2000-06-28",
        "discontinued": "true",
        "process_node_nm": "180",
        "vram_gb": "0.03125",
        "vram_type": "SDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "175",
        "tdp_watts": "12",
        "directx_version": "7.0",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; hardware T&L, fixed-function pipeline. Budget card.",
    },

    # ============ GeForce 256 ============
    "GeForce256": {
        "gpu_chip": "NV10",
        "release_year": "1999",
        "release_date": "1999-10-11",
        "discontinued": "true",
        "process_node_nm": "220",
        "vram_gb": "0.03125",
        "vram_type": "DDR",
        "vram_bus_width_bit": "128",
        "base_clock_mhz": "120",
        "tdp_watts": "20",
        "price_usd_launch": "249",
        "directx_version": "7.0",
        "pcie_generation": "AGP",
        "notes": "Pre-CUDA GPU; first GPU in history with hardware T&L.",
    },

    # ============ NVIDIA Quadro M series (Maxwell) ============
    "NVIDIA Quadro M6000": {
        "architecture": "Maxwell",
        "gpu_chip": "GM200",
        "release_year": "2015",
        "release_date": "2015-03-23",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "12",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "384",
        "cuda_cores": "3072",
        "boost_clock_mhz": "1045",
        "fp32_tflops": "6.43",
        "tdp_watts": "250",
        "price_usd_launch": "5000",
        "directx_version": "12",
        "opencl_version": "1.2",
        "cuda_compute_capability": "5.2",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 4x DisplayPort 1.2",
        "max_displays": "4",
        "notes": "Top Maxwell workstation GPU; full GM200 die.",
    },
    "NVIDIA Quadro M5000": {
        "architecture": "Maxwell",
        "gpu_chip": "GM204",
        "release_year": "2015",
        "release_date": "2015-06-29",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "8",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "256",
        "cuda_cores": "2048",
        "boost_clock_mhz": "861",
        "fp32_tflops": "4.3",
        "tdp_watts": "150",
        "price_usd_launch": "2500",
        "directx_version": "12",
        "opencl_version": "1.2",
        "cuda_compute_capability": "5.2",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 4x DisplayPort 1.2",
        "max_displays": "4",
    },
    "NVIDIA Quadro M4000": {
        "architecture": "Maxwell",
        "gpu_chip": "GM206",
        "release_year": "2015",
        "release_date": "2015-06-29",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "8",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "256",
        "cuda_cores": "1664",
        "boost_clock_mhz": "1075",
        "fp32_tflops": "2.57",
        "tdp_watts": "120",
        "price_usd_launch": "1250",
        "directx_version": "12",
        "opencl_version": "1.2",
        "cuda_compute_capability": "5.2",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "4x DisplayPort 1.2",
        "max_displays": "4",
    },
    "NVIDIA Quadro M2000": {
        "architecture": "Maxwell",
        "gpu_chip": "GM107",
        "release_year": "2016",
        "release_date": "2016-04-11",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "4",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "128",
        "cuda_cores": "768",
        "boost_clock_mhz": "1038",
        "fp32_tflops": "1.19",
        "tdp_watts": "75",
        "price_usd_launch": "599",
        "directx_version": "12",
        "opencl_version": "1.2",
        "cuda_compute_capability": "5.0",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "4x Mini-DisplayPort 1.2",
        "max_displays": "4",
    },

    # ============ NVIDIA Quadro K series (Kepler) ============
    "NVIDIA Quadro K6000": {
        "architecture": "Kepler",
        "gpu_chip": "GK110",
        "release_year": "2013",
        "release_date": "2013-07-23",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "12",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "384",
        "cuda_cores": "2880",
        "boost_clock_mhz": "901",
        "fp32_tflops": "5.19",
        "tdp_watts": "225",
        "price_usd_launch": "5000",
        "directx_version": "11.1",
        "opencl_version": "1.2",
        "cuda_compute_capability": "3.5",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "2x DVI + 2x DisplayPort 1.2",
        "max_displays": "4",
        "notes": "Flagship Kepler workstation GPU; full GK110 die.",
    },
    "NVIDIA Quadro K5200": {
        "architecture": "Kepler",
        "gpu_chip": "GK110",
        "release_year": "2013",
        "release_date": "2013-09-17",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "8",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "256",
        "cuda_cores": "2304",
        "boost_clock_mhz": "771",
        "fp32_tflops": "3.55",
        "tdp_watts": "150",
        "price_usd_launch": "2500",
        "directx_version": "11.1",
        "opencl_version": "1.2",
        "cuda_compute_capability": "3.5",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "2x DVI + 2x DisplayPort 1.2",
        "max_displays": "4",
    },
    "NVIDIA Quadro K5000": {
        "architecture": "Kepler",
        "gpu_chip": "GK104",
        "release_year": "2012",
        "release_date": "2012-08-14",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "4",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "256",
        "cuda_cores": "1536",
        "boost_clock_mhz": "901",
        "fp32_tflops": "2.77",
        "tdp_watts": "122",
        "price_usd_launch": "2249",
        "directx_version": "11.1",
        "opencl_version": "1.2",
        "cuda_compute_capability": "3.0",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "2x DVI + 2x DisplayPort 1.2",
        "max_displays": "4",
    },
    "NVIDIA Quadro K4200": {
        "architecture": "Kepler",
        "gpu_chip": "GK107",
        "release_year": "2014",
        "release_date": "2014-01-13",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "4",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "128",
        "cuda_cores": "1344",
        "boost_clock_mhz": "784",
        "fp32_tflops": "2.11",
        "tdp_watts": "105",
        "price_usd_launch": "1200",
        "directx_version": "11.1",
        "opencl_version": "1.2",
        "cuda_compute_capability": "3.0",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 2x DisplayPort 1.2",
        "max_displays": "4",
    },
    "NVIDIA Quadro K4000": {
        "architecture": "Kepler",
        "gpu_chip": "GK106",
        "release_year": "2013",
        "release_date": "2013-03-04",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "3",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "192",
        "cuda_cores": "768",
        "boost_clock_mhz": "810",
        "fp32_tflops": "1.24",
        "tdp_watts": "80",
        "price_usd_launch": "799",
        "directx_version": "11.1",
        "opencl_version": "1.2",
        "cuda_compute_capability": "3.0",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 2x DisplayPort 1.2",
        "max_displays": "4",
    },
    "NVIDIA Quadro K2200": {
        "architecture": "Maxwell",
        "gpu_chip": "GM107",
        "release_year": "2014",
        "release_date": "2014-09-22",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "4",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "128",
        "cuda_cores": "640",
        "boost_clock_mhz": "1045",
        "fp32_tflops": "1.34",
        "tdp_watts": "68",
        "price_usd_launch": "550",
        "directx_version": "12",
        "opencl_version": "1.2",
        "cuda_compute_capability": "5.0",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 2x DisplayPort 1.2",
        "max_displays": "4",
        "notes": "Maxwell-based Quadro despite K-series branding.",
    },
    "NVIDIA Quadro K2000": {
        "architecture": "Kepler",
        "gpu_chip": "GK107",
        "release_year": "2013",
        "release_date": "2013-03-04",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "2",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "128",
        "cuda_cores": "384",
        "boost_clock_mhz": "950",
        "fp32_tflops": "0.73",
        "tdp_watts": "51",
        "price_usd_launch": "399",
        "directx_version": "11.1",
        "opencl_version": "1.2",
        "cuda_compute_capability": "3.0",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 2x Mini-DisplayPort 1.2",
        "max_displays": "3",
    },
    "NVIDIA Quadro K1200": {
        "architecture": "Maxwell",
        "gpu_chip": "GM107",
        "release_year": "2015",
        "release_date": "2015-03-23",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "4",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "128",
        "cuda_cores": "512",
        "boost_clock_mhz": "1058",
        "fp32_tflops": "1.08",
        "tdp_watts": "45",
        "price_usd_launch": "329",
        "directx_version": "12",
        "opencl_version": "1.2",
        "cuda_compute_capability": "5.0",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 2x Mini-DisplayPort 1.2",
        "max_displays": "3",
        "notes": "Maxwell-based Quadro despite K-series branding. Low-profile capable.",
    },
    "NVIDIA Quadro K620": {
        "architecture": "Maxwell",
        "gpu_chip": "GM107",
        "release_year": "2014",
        "release_date": "2014-09-22",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "2",
        "vram_type": "GDDR5",
        "vram_bus_width_bit": "64",
        "cuda_cores": "384",
        "boost_clock_mhz": "1045",
        "fp32_tflops": "0.80",
        "tdp_watts": "41",
        "price_usd_launch": "199",
        "directx_version": "12",
        "opencl_version": "1.2",
        "cuda_compute_capability": "5.0",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 1x Mini-DisplayPort 1.2",
        "max_displays": "2",
        "notes": "Maxwell-based Quadro despite K-series branding. Low-profile capable.",
    },
    "NVIDIA Quadro K420": {
        "architecture": "Kepler",
        "gpu_chip": "GK107",
        "release_year": "2014",
        "release_date": "2014-01-13",
        "discontinued": "true",
        "process_node_nm": "28",
        "vram_gb": "1",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "64",
        "cuda_cores": "192",
        "boost_clock_mhz": "876",
        "fp32_tflops": "0.34",
        "tdp_watts": "41",
        "price_usd_launch": "149",
        "directx_version": "11.1",
        "opencl_version": "1.2",
        "cuda_compute_capability": "3.0",
        "pcie_generation": "PCIe 3.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 1x VGA",
        "max_displays": "2",
        "notes": "Entry-level Kepler workstation GPU. Low-profile capable.",
    },

    # ============ NVIDIA Quadro FX series ============
    "NVIDIA Quadro FX 5800": {
        "architecture": "Tesla",
        "gpu_chip": "GT200",
        "release_year": "2008",
        "release_date": "2008-11-11",
        "discontinued": "true",
        "process_node_nm": "65",
        "vram_gb": "4",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "512",
        "cuda_cores": "240",
        "base_clock_mhz": "610",
        "fp32_tflops": "0.66",
        "tdp_watts": "189",
        "price_usd_launch": "3499",
        "directx_version": "10.0",
        "opencl_version": "1.0",
        "cuda_compute_capability": "1.3",
        "pcie_generation": "PCIe 2.0",
        "pcie_lanes": "16",
        "display_outputs": "2x DVI + 1x Stereo",
        "max_displays": "2",
        "notes": "Flagship Quadro FX; first workstation GPU with 4GB VRAM.",
    },
    "NVIDIA Quadro FX 580": {
        "architecture": "Tesla",
        "gpu_chip": "G96",
        "release_year": "2008",
        "release_date": "2008-04-08",
        "discontinued": "true",
        "process_node_nm": "65",
        "vram_gb": "0.5",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "128",
        "cuda_cores": "32",
        "base_clock_mhz": "450",
        "tdp_watts": "40",
        "directx_version": "10.0",
        "opencl_version": "1.0",
        "cuda_compute_capability": "1.1",
        "pcie_generation": "PCIe 2.0",
        "pcie_lanes": "16",
        "display_outputs": "2x DisplayPort 1.0 + 1x DVI",
        "max_displays": "2",
    },
    "NVIDIA Quadro FX 4800": {
        "architecture": "Tesla",
        "gpu_chip": "GT200",
        "release_year": "2008",
        "release_date": "2008-11-11",
        "discontinued": "true",
        "process_node_nm": "55",
        "vram_gb": "1.5",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "384",
        "cuda_cores": "192",
        "base_clock_mhz": "602",
        "fp32_tflops": "0.52",
        "tdp_watts": "150",
        "price_usd_launch": "1799",
        "directx_version": "10.0",
        "opencl_version": "1.0",
        "cuda_compute_capability": "1.3",
        "pcie_generation": "PCIe 2.0",
        "pcie_lanes": "16",
        "display_outputs": "1x DVI + 2x DisplayPort 1.0",
        "max_displays": "2",
        "notes": "Popular for Mac Pro systems.",
    },
    "NVIDIA Quadro FX 3800": {
        "architecture": "Tesla",
        "gpu_chip": "G92",
        "release_year": "2009",
        "release_date": "2009-04-01",
        "discontinued": "true",
        "process_node_nm": "55",
        "vram_gb": "1",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "256",
        "cuda_cores": "192",
        "base_clock_mhz": "600",
        "fp32_tflops": "0.23",
        "tdp_watts": "95",
        "price_usd_launch": "799",
        "directx_version": "10.0",
        "opencl_version": "1.0",
        "cuda_compute_capability": "1.1",
        "pcie_generation": "PCIe 2.0",
        "pcie_lanes": "16",
        "display_outputs": "2x DVI + 1x DisplayPort 1.0",
        "max_displays": "2",
    },
    "NVIDIA Quadro FX 1800": {
        "architecture": "Tesla",
        "gpu_chip": "G94",
        "release_year": "2009",
        "release_date": "2009-04-01",
        "discontinued": "true",
        "process_node_nm": "55",
        "vram_gb": "0.75",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "192",
        "cuda_cores": "64",
        "base_clock_mhz": "550",
        "fp32_tflops": "0.14",
        "tdp_watts": "60",
        "price_usd_launch": "499",
        "directx_version": "10.0",
        "opencl_version": "1.0",
        "cuda_compute_capability": "1.1",
        "pcie_generation": "PCIe 2.0",
        "pcie_lanes": "16",
        "display_outputs": "2x DVI",
        "max_displays": "2",
    },
    "NVIDIA Quadro FX 380": {
        "architecture": "Tesla",
        "gpu_chip": "G96",
        "release_year": "2009",
        "release_date": "2009-04-01",
        "discontinued": "true",
        "process_node_nm": "55",
        "vram_gb": "0.25",
        "vram_type": "GDDR3",
        "vram_bus_width_bit": "128",
        "cuda_cores": "32",
        "base_clock_mhz": "450",
        "tdp_watts": "34",
        "price_usd_launch": "199",
        "directx_version": "10.0",
        "opencl_version": "1.0",
        "cuda_compute_capability": "1.1",
        "pcie_generation": "PCIe 2.0",
        "pcie_lanes": "16",
        "display_outputs": "2x DisplayPort 1.0 + 1x DVI",
        "max_displays": "2",
    },

    # ============ NVIDIA RTX A series (Ampere professional) ============
    "NVIDIA RTX A6000": {
        "architecture": "Ampere",
        "gpu_chip": "GA102",
        "release_year": "2020",
        "release_date": "2020-10-05",
        "discontinued": "true",
        "process_node_nm": "8",
        "vram_gb": "48",
        "vram_type": "GDDR6",
        "vram_bus_width_bit": "384",
        "cuda_cores": "10752",
        "tensor_cores": "336",
        "rt_cores": "84",
        "boost_clock_mhz": "1860",
        "fp32_tflops": "38.71",
        "tdp_watts": "300",
        "price_usd_launch": "4500",
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": "8.6",
        "ecc_support": "true",
        "pcie_generation": "PCIe 4.0",
        "pcie_lanes": "16",
        "display_outputs": "4x DisplayPort 1.4a",
        "max_displays": "4",
        "notes": "Top Ampere workstation GPU; full GA102 die with ECC GDDR6.",
    },
    "NVIDIA RTX A5000": {
        "architecture": "Ampere",
        "gpu_chip": "GA102",
        "release_year": "2021",
        "release_date": "2021-04-12",
        "discontinued": "true",
        "process_node_nm": "8",
        "vram_gb": "24",
        "vram_type": "GDDR6",
        "vram_bus_width_bit": "384",
        "cuda_cores": "8192",
        "tensor_cores": "256",
        "rt_cores": "64",
        "boost_clock_mhz": "1695",
        "fp32_tflops": "27.77",
        "tdp_watts": "230",
        "price_usd_launch": "2750",
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": "8.6",
        "ecc_support": "true",
        "pcie_generation": "PCIe 4.0",
        "pcie_lanes": "16",
        "display_outputs": "4x DisplayPort 1.4a",
        "max_displays": "4",
    },
    "NVIDIA RTX A4000": {
        "architecture": "Ampere",
        "gpu_chip": "GA104",
        "release_year": "2021",
        "release_date": "2021-04-12",
        "discontinued": "true",
        "process_node_nm": "8",
        "vram_gb": "16",
        "vram_type": "GDDR6",
        "vram_bus_width_bit": "256",
        "cuda_cores": "6144",
        "tensor_cores": "192",
        "rt_cores": "48",
        "boost_clock_mhz": "1560",
        "fp32_tflops": "19.17",
        "tdp_watts": "140",
        "price_usd_launch": "950",
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": "8.6",
        "ecc_support": "true",
        "pcie_generation": "PCIe 4.0",
        "pcie_lanes": "16",
        "display_outputs": "4x Mini-DisplayPort 1.4a",
        "max_displays": "4",
    },
    "NVIDIA RTX A2000": {
        "architecture": "Ampere",
        "gpu_chip": "GA106",
        "release_year": "2021",
        "release_date": "2021-08-10",
        "discontinued": "true",
        "process_node_nm": "8",
        "vram_gb": "8",
        "vram_type": "GDDR6",
        "vram_bus_width_bit": "192",
        "cuda_cores": "3328",
        "tensor_cores": "104",
        "rt_cores": "26",
        "boost_clock_mhz": "1620",
        "fp32_tflops": "7.99",
        "tdp_watts": "70",
        "price_usd_launch": "449",
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": "8.6",
        "ecc_support": "true",
        "pcie_generation": "PCIe 4.0",
        "pcie_lanes": "16",
        "display_outputs": "4x Mini-DisplayPort 1.4",
        "max_displays": "4",
        "notes": "Entry-level Ampere workstation GPU; low-profile capable.",
    },
    "NVIDIA RTX A16": {
        "architecture": "Ampere",
        "gpu_chip": "GA107",
        "release_year": "2022",
        "release_date": "2022-04-12",
        "discontinued": "true",
        "process_node_nm": "8",
        "vram_gb": "16",
        "vram_type": "GDDR6",
        "vram_bus_width_bit": "128",
        "cuda_cores": "2560",
        "tensor_cores": "80",
        "rt_cores": "20",
        "boost_clock_mhz": "1785",
        "fp32_tflops": "4.55",
        "tdp_watts": "250",
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": "8.6",
        "pcie_generation": "PCIe 4.0",
        "pcie_lanes": "16",
        "notes": "Multi-GPU server card; 250W TDP is total for 4 GPUs on board (approx 62.5W each).",
    },
    "NVIDIA RTX A10": {
        "architecture": "Ampere",
        "gpu_chip": "GA102",
        "release_year": "2021",
        "release_date": "2021-05-13",
        "discontinued": "true",
        "process_node_nm": "8",
        "vram_gb": "24",
        "vram_type": "GDDR6",
        "vram_bus_width_bit": "384",
        "cuda_cores": "9216",
        "tensor_cores": "288",
        "rt_cores": "72",
        "boost_clock_mhz": "1920",
        "fp32_tflops": "31.02",
        "tdp_watts": "150",
        "price_usd_launch": "2999",
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": "8.6",
        "ecc_support": "true",
        "pcie_generation": "PCIe 4.0",
        "pcie_lanes": "16",
        "notes": "Passively cooled server/workstation GPU; no display outputs.",
    },
    "NVIDIA RTX A2": {
        "architecture": "Ampere",
        "gpu_chip": "GA107",
        "release_year": "2022",
        "release_date": "2022-02-14",
        "discontinued": "true",
        "process_node_nm": "8",
        "vram_gb": "16",
        "vram_type": "GDDR6",
        "vram_bus_width_bit": "128",
        "cuda_cores": "1280",
        "tensor_cores": "40",
        "rt_cores": "10",
        "boost_clock_mhz": "1740",
        "fp32_tflops": "4.46",
        "tdp_watts": "60",
        "price_usd_launch": "599",
        "directx_version": "12 Ultimate",
        "opencl_version": "3.0",
        "cuda_compute_capability": "8.6",
        "ecc_support": "true",
        "pcie_generation": "PCIe 4.0",
        "pcie_lanes": "16",
        "notes": "Entry-level Ampere server GPU; passively cooled, low-profile.",
    },
}


def main():
    # Read the CSV
    with open(CSV_PATH, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        rows = list(reader)

    print(f"Read {len(rows)} rows with {len(fieldnames)} columns.")

    updated_count = 0
    not_found = []

    for card_name, card_specs in CARDS.items():
        found = False
        for row in rows:
            if row["gpu_name"] == card_name:
                found = True
                fields_updated = 0
                for col, value in card_specs.items():
                    # Only fill if currently null or empty
                    current = row.get(col, "")
                    if current in ("", "null", "None", None):
                        row[col] = value
                        fields_updated += 1
                # Always set discontinued and last_modified
                row["discontinued"] = "true"
                row["last_modified"] = TIMESTAMP
                print(f"  Updated '{card_name}': {fields_updated} fields filled")
                updated_count += 1
                break
        if not found:
            not_found.append(card_name)

    if not_found:
        print(f"\nWARNING: {len(not_found)} cards not found in CSV:")
        for name in not_found:
            print(f"  - {name}")

    # Write back
    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"\nDone. Updated {updated_count} cards. CSV saved to {CSV_PATH}")


if __name__ == "__main__":
    main()
